apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-nusi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-nusi
    app.kubernetes.io/part-of: vote-ui
  name: devfile-sample-dotnet60-basic-nusi
  namespace: nvinto-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-nusi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-nusi
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:2bbbc8eeb5819d54e4bdd3a35119bedacc8cddcfb9829e249ced64f3fba98638
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
